export const AUTH = 'AUTH'
export const AUTH_GOOGLE = 'AUTH_GOOGLE'
export const LOGOUT = 'LOGOUT'
export const ERROR = 'ERROR'
export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'